[package]
name = "advent_of_code_2025"
description = "Advent of Code solutions for 2025"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
advent_lib = { workspace = true }
anyhow = { workspace = true }
